#!/usr/bin/env python3

"""
This module contains a coroutine wich collects 10 randoms numbers.
"""


from typing import List


async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Coroutine that collects 10 numbers with generated by `async_generator`.
    Return a list of floats.
    """
    return [i async for i in async_generator()]
