#!/usr/bin/env python3

"""
This module contains a coroutine wich collects 10 randoms numbers.
"""

import asyncio
import time


async_comprehension = __import__('1-async_comprehension').async_comprehension


async def measure_runtime() -> float:
    """
    Coroutine that collects 10 numbers with generated by `async_generator`.
    Return a list of floats.
    """
    start_time = time.perf_counter()
    await asyncio.gather(
        async_comprehension()
    )
    end_time = time.perf_counter()
    total_time = end_time - start_time
    return total_time
